#!/usr/bin/env bash

# This will set the path to the packages list file

packages=./list_packages.txt

# This checks if the packages file exists and if it does not it will print an error message and exit

if [[ ! -f $packages ]]; then
  echo "Packages list $packages not found"
  exit 1
fi

# This will loop through each package listed in the packages.txt file
while read -r package_list; do

  if pacman -Qs "$package_list" > /dev/null; then
  
    # If the package is found, print it is already installed
    echo "$package_list has already been installed"
  else
  # If the package is not found, then install the package
    echo "installing $package_list"
    pacman -S --noconfirm "$package_list"
  fi
done < $packages
  


