#!/usr/bin/env bash

# ================================
# File Name: install_packages
# Author: Karnveer Basra
# Created: 04-11-2024
# Description: script that reads the plain text file list_packages.txt and it installs each listed package.
# Sources:
#   [1]: Pacman -f - https://wiki.archlinux.org/title/Pacman
#   [2]: While read - https://earthly.dev/blog/bash-read-files/ and https://stackoverflow.com/questions/5057083/read-a-file-using-a-bash-script
#   [3]: Using pacman -Qs - Pacman Manul
# ================================

# This will set the path to the packages list file

packages=./list_packages.txt

# This checks if the packages file exists and if it does not it will print an error message and exit

if [[ ! -f $packages ]]; then
  echo "Packages list $packages not found"
  exit 1
fi

# This will loop through each package listed in the packages.txt file
while read -r package_list; do

  if pacman -Qs "$package_list" > /dev/null; then
  
    # If the package is found, print it is already installed
    echo "$package_list has already been installed"
  else
  # If the package is not found, then install the package
    echo "installing $package_list"
    pacman -S --noconfirm "$package_list"
  fi
done < $packages
  


