#!/usr/bin/env bash



# ================================
# File Name: main_script
# Author: Karnveer Basra
# Created: 06-11-2024
# Description: Script that calls both install_packages and symlink_project
#   [1]: UID checker - https://nick3499.medium.com/bash-uid-0-root-user-confirmation-c091ca6ca216#:~:text=The%20if%20%5B%20%24UID%20%2Dne,echo%20%24UID%20will%20return%200%20.
#   [2]: usage, getopts, shift - https://gitlab.com/cit2420/2420-notes-f24/-/blob/main/2420-notes/week-seven.md
# ================================

# This will check if the user is running the script with root or sudo

if [[ "$UID" -ne 0 ]]; then
    # if its not being ran with correct privileges, it will print the message
  echo "This script must be run as root. Please use sudo."
  exit 1
fi

# Defining the usage function for help details
usage() {
  echo "Usage: $0 [-t] [-h] [-p] [-c]"
  echo ""
  echo "    -t  --two scripts   Execute the two scripts install_packages + symlink_script"
  echo "    -h, --help          Show help"
  echo "    -p, --packages      Run the install_packages script"
  echo "    -c, --symlink       Executes the symlink_script"
  echo ""
  exit 1
}

#getopts to get the options above
while getopts ":thpc" opt; do
  case "${opt}" in
    t) # Execution of both scripts install_packages and symlink_script
      echo "Executing install_packages and symlink_script"
      ./install_packages
      ./symlink_script
      exit 0
      ;;
    h) # Displays help information
      usage
      ;;
    p) # Only runs the install_packages script
      echo "Running install_packages script"
      ./install_packages
      exit 0
      ;;
    c) # Executes symlink_script only
      echo "Executing symlink_script"
      ./symlink_script
      exit 0
      ;;
    
    ?) # Invalid option 
      echo "Invalid Option, Refer to Usage -h"
      usage
      ;;
  esac
done

# Checks if no aruguments or addiotional arguments
shift $((OPTIND - 1))

# Check if there are positional parameters or not
if [[ $# -lt 1 ]]; then
  echo "You need to provide an option -t, -h, -p or -c"
  exit 1
fi
